version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: llama3
    ports:
      - '11434:11434'
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama-data:
